name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15
  - pip
  - mlflow=2.10.0
  - scikit-learn=1.3.2
  - pandas=1.5.3
  - numpy=1.23.5
  - jupyterlab
  - ipykernel
  - matplotlib
  - pyarrow
  - pyyaml
  - click
  - requests
  - tqdm
  - seaborn
  - pip:
      - hydra-core==1.3.2
      - wandb==0.16.6

